In [ ]:
What is a database? Differentiate between SQL and NoSQL databases.

Ans ->
A database is an organized collection of data stored in a computer system. It is designed to efficiently store, retrieve, and manage large amounts of information. 
Databases are widely used in applications such as websites, banking systems, inventory management systems, and more.

SQL databases are based on the relational model and use SQL for querying and managing data. Data in SQL databases is organized into tables with predefined schema and relationships between tables.

SQL databases are known for their ability to enforce data integrity, consistency, and ACID (Atomicity, Consistency, Isolation, and Durability) properties. Examples of SQL databases include MySQL, Oracle, SQL Server, and PostgreSQL.
On the other hand, NoSQL databases use a variety of data models to store data, including document, key-value, graph, and column-family stores. NoSQL databases do not rely on fixed schemas, and they offer flexible data modeling capabilities.

NoSQL databases are designed to scale horizontally, which makes them a popular choice for web applications that require high scalability and performance. Examples of NoSQL databases include MongoDB, Cassandra, Redis, and Amazon DynamoDB.
In summary, the main difference between SQL and NoSQL databases is in the way they store and manage data. SQL databases are based on the relational model, have predefined schemas, and use SQL for querying and managing data.
NoSQL databases, on the other hand, offer flexible data modeling capabilities, and do not rely on fixed schemas. They use various data models and offer horizontal scalability. The choice between SQL and NoSQL databases depends on the specific requirements of the application, such as scalability, performance, data consistency, and flexibility.

In [ ]:
Q2 -> What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

Ans -> DDL (Data Definition Language) is a set of SQL commands used to create, modify, and delete database objects such as tables, indexes, and views. DDL commands are used to define the structure of the database schema and its objects.

The four most commonly used DDL commands in SQL are CREATE, DROP, ALTER, and TRUNCATE. Here's an explanation of each command and an example:

CREATE - This command is used to create a new table or other database objects. For example, the following SQL code creates a new table named customers:
    
# example 
create table customer (
    id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    age INT 
);

DROP - This command is used to delete an existing database object. For example, the following SQL code drops the customers table:

# rxample of drop 

DROP TABLE customers;

ALTER - This command is used to modify the structure of an existing database object. For example, the following SQL code adds a new column phone to the customers table:
    
ALTER TABLE customers ADD COLOUMN phone VARCHAR(28);

TRUNCATE - This command is used to delete all data from an existing table. For example, the following SQL code truncates the customers table:
    
# example of truncate 
TRUNCATE TABLE customers;

In [ ]:
Q3 -> What is DML? Explain INSERT, UPDATE, and DELETE with an example.

Ans -> DML (Data Manipulation Language) is a set of SQL commands used to manipulate data in a database. DML commands are used to insert, update, and delete data from database tables.
The three most commonly used DML commands in SQL are INSERT, UPDATE, and DELETE. Here's an explanation of each command and an example:

INSERT - This command is used to insert new data into a table. For example, the following SQL code inserts a new row into the customers table:

#  inssert example   
INSERT INTO customers (id , name, email , age)
VALUES(1, 'John DOe' , 'john@example.com' , 25)

UPDATE - This command is used to update existing data in a table. For example, the following SQL code updates the email address of the customer with id 1 in the customers table:
# example of update

UPDATE customers 
SET email = 'jddoe@example.com';
WHERE id = 1;

DELETE - This command is used to delete data from a table. For example, the following SQL code deletes the customer with id 1 from the customers table:
    
# example of delete 
DELETE FROM customer 
Where id = 1;

In [ ]:
Q3 -> What is DQL? Explain SELECT with an example.

Ans -> DQL (Data Query Language) is a set of SQL commands used to retrieve data from a database. DQL commands are used to query database tables to retrieve specific data based on certain criteria.

The most commonly used DQL command in SQL is SELECT. Here's an explanation of the SELECT command and an example:

SELECT - This command is used to retrieve data from a database table. For example, the following SQL code retrieves all rows and columns from the customers table:

# example of select 
SELECT * from customers;

In [ ]:
Q4 -> Explain Primary Key and Foreign Key.

Ans -> Primary key and foreign key are two important concepts in relational databases that are used to establish relationships between tables.

A primary key is a column or set of columns in a table that uniquely identifies each row in that table. A primary key is used to enforce the entity integrity constraint, which ensures that each row in a table is unique and can be identified using a unique identifier. 

The primary key of a table can be used as a reference by other tables to establish relationships between them.

A foreign key, on the other hand, is a column or set of columns in a table that refers to the primary key of another table. A foreign key is used to establish relationships between tables, and it ensures that the data in the tables remains consistent and accurate.

The foreign key in a table references the primary key of another table, and it can be used to enforce the referential integrity constraint, which ensures that the data in the tables is consistent and accurate.

In [ ]:
Q6 -> Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

Ans -> To connect to MySQL from Python, you can use the mysql-connector-python module. Here is an example code that connects to a MySQL database and executes a simple query:
    
import mysql.connector 

cnx = mysql.connector.connect(user = 'username' , password = 'password' ,
                             host = 'localhost',
                             database = 'database_name')

cursor = cnx.cursor()
query = 'SELECT * FROM table_name'
cursor.execute(query)

result = cursor.fetchall()
for row in results:
    print(row)
cursor.close()
cnx.close()

The cursor() method returns a cursor object that can be used to execute queries and fetch the results. The execute() method of the cursor object is used to execute a query, which is passed as a parameter. In this example, we execute a simple query to retrieve all the rows from a table.

The fetchall() method is used to fetch all the rows returned by the query. The results are stored in the results variable, which can then be iterated over and printed.

In [ ]:
Q7 -> Give the order of execution of SQL clauses in an SQL query.

Ans -> 
1) FROM clause: This clause specifies the table(s) or view(s) from which the data is to be retrieved.

2) WHERE clause: This clause filters the rows based on a specified condition.

3) GROUP BY clause: This clause groups the rows based on one or more columns.

4) HAVING clause: This clause filters the groups based on a specified condition.

5) SELECT clause: This clause specifies the columns to be retrieved.

6) ORDER BY clause: This clause sorts the result set based on one or more columns.